In [12]:
# Para istalar uma biblioteca comando:
# no colab e !pip install
# fora do colab e pip install
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
#para colocar a biblioteca em uso, devemos importar ela
#estrutura import nome biblioteca as apelido
import pandas as pd

In [16]:
dados ={
    'nome':['Giovanni','Arlindo','Felizardo','Aida '],
    'idade':[36,24,20,22],
    'cidade':['campinas','campinas','Moscovo','Luanda']
}
# A bibliteca panda pode tranformar um dicionario em uma tabela.
#que é chamdo de dataframe
df_dados= pd.DataFrame(dados)
display(df_dados)

        nome  idade    cidade
0   Giovanni     36  campinas
1    Arlindo     24  campinas
2  Felizardo     20   Moscovo
3      Aida      22    Luanda

In [18]:
#criar um arquivo sem nada
#arquivo csv(Excel)
#para criar precisamos de dados e do pandas
#chamando dados e atribuindo função
df_dados.to_csv("teste_de_dados.csv", index=False)

In [27]:
#como ler um arquivo que me enviaram
df_ler_dados=pd.read_csv('/content/teste_de_dados.csv')

#comando para ler as primeiras infos do arquivo
df_ler_dados.head()

        nome  idade    cidade
0   Giovanni     36  campinas
1    Arlindo     24  campinas
2  Felizardo     20   Moscovo
3      Aida      22    Luanda

In [28]:
#vamos popular (Adicionando novos dados) a tabela
novos_dados={
    'nome':['josimar','Edmara','Donald'],
    'idade':[35,19,23],
    'cidade':['Canada','Paris','Paris']
}
#transformandondo dicionario em dados
df_novos_dados=pd.DataFrame(novos_dados)
#unindo o antigo e o novo
#concatenação=junta ou unir
df_dados_juntos = pd.concat([df_dados,df_novos_dados], ignore_index=True)
display(df_dados_juntos)

        nome  idade    cidade
0   Giovanni     36  campinas
1    Arlindo     24  campinas
2  Felizardo     20   Moscovo
3      Aida      22    Luanda
4    josimar     35    Canada
5     Edmara     19     Paris
6     Donald     23     Paris