In [ ]:
# importando dados do github
#maneira 1 - copiando todas as informações
#git clone 
# 1 baixar um repositório

In [6]:
#maneira 2 - importação via Raw 
#importação unitaria de um arquivo específico
#url do raw do arquivo
arquivo_1 = 'https://raw.githubusercontent.com/ChiaviniK/import-de-dados-com-python/refs/heads/main/example_data.csv'
arquivo_2 = 'https://raw.githubusercontent.com/ChiaviniK/import-de-dados-com-python/refs/heads/main/example_data.json'
arquivo_3 = 'https://github.com/ChiaviniK/import-de-dados-com-python/raw/refs/heads/main/example_data.xlsx'
arquivo_4 = 'https://raw.githubusercontent.com/ChiaviniK/import-de-dados-com-python/refs/heads/main/sample_data.csv'
#para importar os arquivos, basta usar a função de leitura do pandas
import pandas as pd
#csv 
df_csv_example= pd.read_csv(arquivo_1)
display(df_csv_example)
#json
df_json = pd.read_json(arquivo_2)
display(df_json)
#xlsx
#sempre que for um excel devo usar o engine 'openpyxl' para evitar erros de leitura
df_xlsx = pd.read_excel(arquivo_3, engine='openpyxl')
display(df_xlsx)
#csv2
df_csv2_sample = pd.read_csv(arquivo_4)
display(df_csv2_sample)

      Name  Age  Score
0    Alice   23     88
1      Bob   34     92
2  Charlie   45     95
3    David   28     78
4      Eve   30     85

                                           employees
0  {'name': 'Alice', 'age': 28, 'department': {'n...
1  {'name': 'Bob', 'age': 34, 'department': {'nam...
2  {'name': 'Charlie', 'age': 45, 'department': {...

      Name  Age  Score
0    Alice   23     88
1      Bob   34     92
2  Charlie   45     95
3    David   28     78
4      Eve   30     85

   id     name   age   department  salary
0   1    Alice  28.0  Engineering   75000
1   2      Bob   NaN        Sales   64000
2   3  Charlie  34.0           HR   72000
3   4    David  29.0  Engineering   69000
4   5      Eve   NaN    Marketing   60000